"""Site export — any admin can download the full site for independent redeployment."""

import io
import shutil
import tempfile
import zipfile
from pathlib import Path

from fastapi import APIRouter, Depends
from fastapi.responses import StreamingResponse

from convocation.auth.deps import require_officer
from convocation.auth.models import User
from convocation.config import settings
from convocation.content.store import ContentStore

router = APIRouter(prefix="/api/export", tags=["export"])


@router.get("/site")
async def export_site(user: User = Depends(require_officer)):
    """Export the complete site as a self-contained zip.

    Includes:
    - All content (git repo bundle for full history)
    - Site templates
    - Static assets
    - Generated HTML output
    - Docker configuration for independent deployment
    - .env.example with sanitized configuration
    - README with setup instructions
    """

    buf = io.BytesIO()
    store = ContentStore()

    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        # Content repo as git bundle (preserves full history)
        with tempfile.TemporaryDirectory() as tmpdir:
            bundle_path = store.export_bundle(Path(tmpdir))
            zf.write(bundle_path, "convocation-export/content-repo.bundle")

        # Templates
        template_dir = Path(__file__).parent.parent / "templates"
        _add_dir_to_zip(zf, template_dir, "convocation-export/templates")

        # Static assets
        static_dir = Path(__file__).parent.parent / "static"
        if static_dir.exists():
            _add_dir_to_zip(zf, static_dir, "convocation-export/static")

        # Generated output
        output_dir = settings.output_abs_path
        if output_dir.exists():
            _add_dir_to_zip(zf, output_dir, "convocation-export/output")

        # Sanitized .env.example
        zf.writestr("convocation-export/.env.example", _sanitized_env())

        # Docker files
        project_root = Path(__file__).parent.parent.parent
        for fname in ("Dockerfile", "docker-compose.yml", "pyproject.toml"):
            fpath = project_root / fname
            if fpath.exists():
                zf.write(fpath, f"convocation-export/{fname}")

        # README
        zf.writestr("convocation-export/README.md", _export_readme())

    buf.seek(0)
    return StreamingResponse(
        buf,
        media_type="application/zip",
        headers={"Content-Disposition": "attachment; filename=convocation-export.zip"},
    )


def _add_dir_to_zip(zf: zipfile.ZipFile, source_dir: Path, archive_prefix: str):
    """Recursively add a directory to a zip file."""
    for fp in source_dir.rglob("*"):
        if fp.is_file() and "__pycache__" not in str(fp):
            arcname = f"{archive_prefix}/{fp.relative_to(source_dir)}"
            zf.write(fp, arcname)


def _sanitized_env() -> str:
    return """# ConvocAItion Configuration
# Generated from site export — fill in your values

SECRET_KEY=generate-a-new-secret-key
LLM_PROVIDER=anthropic
LLM_BASE_URL=https://api.anthropic.com
LLM_API_KEY=your-api-key
LLM_MODEL=claude-haiku-4-5-20251001
SITE_TITLE={site_title}
SITE_DESCRIPTION={site_description}
SITE_URL=http://localhost:8080
DISCORD_WEBHOOK_URL=
VAPID_PRIVATE_KEY=
VAPID_PUBLIC_KEY=
VAPID_CLAIMS_EMAIL=admin@example.com
BOOTSTRAP_ADMIN_EMAIL=admin@example.com
BOOTSTRAP_ADMIN_PASSWORD=change-me-immediately
""".format(site_title=settings.site_title, site_description=settings.site_description)


def _export_readme() -> str:
    return """# ConvocAItion Site Export

This is a complete export of a ConvocAItion site, including full content history.

## Quick Start

1. Install Python 3.11+ and Git
2. Copy `.env.example` to `.env` and fill in your values
3. Restore the content repository:
   ```bash
   git clone content-repo.bundle content-repo
   ```
4. Install and run:
   ```bash
   pip install -e .
   uvicorn convocation.main:app --host 0.0.0.0 --port 8080
   ```

Or use Docker:
   ```bash
   docker compose up -d
   ```

## What's Included

- **content-repo.bundle** — Full git history of all content (announcements, events, pages, members)
- **templates/** — Jinja2 templates for the public site
- **static/** — CSS, JS, and other assets
- **output/** — Pre-generated static HTML (ready to serve)
- **Dockerfile** + **docker-compose.yml** — Container deployment
- **pyproject.toml** — Python dependencies

## Content Recovery

The content bundle contains complete git history. You can inspect it:
```bash
git clone content-repo.bundle content-repo
cd content-repo
git log --oneline
```

Every change ever made is preserved — who made it, when, and what the diff was.

---
Generated by ConvocAItion — Your community's site. Owned by everyone.
"""
